title: Re-USED
email: info@re-used.com
description: A platform for recycling and reusing materials sustainably.

baseurl: "/Re-USED"
url: "https://valuechainhackers.github.io"

theme: minima

plugins:
  - jekyll-feed
